# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseGo < Formula
  desc "The description of the project
"
  homepage "https://github.com/tcurdt/release-go"
  version "1.0.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_darwin_amd64.zip"
      sha256 "22fedaae7a6d9faa03cdb70778cd35fe4474febe5dab181f41c7cd25bc10d35e"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_darwin_arm64.zip"
      sha256 "35c79768f864a7ae933fc73fd5fd2fb5d2a71741633efd9acf4fa6d73fff293e"

      def install
        bin.install "release-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_linux_arm64.zip"
      sha256 "9e14383fad560b855e242dabe34b6347b4884cacaa78433efe48ddbc343f6a72"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_linux_amd64.zip"
      sha256 "d541292f46d307d2a15e036cf983fde64ab0c386b272f2215570e86e24fa1a96"

      def install
        bin.install "release-go"
      end
    end
  end
end
