# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseGo < Formula
  desc ""
  homepage "https://github.com/tcurdt/release-go"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_darwin_amd64.tar.gz"
      sha256 "83bce4935505104edeb280f6c950d07d61e2b0991345017526398ecaddb33786"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_darwin_arm64.tar.gz"
      sha256 "77f2e8b428467babe158cb0fa90eb52f4f13afa006f98882108abeece9fb8c61"

      def install
        bin.install "release-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_linux_arm64.tar.gz"
      sha256 "7de84a17364beb140acf964711f73cb7ddd11879ac93d06a30a7b6afa35a9185"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.0/release-go_1.0.0_linux_amd64.tar.gz"
      sha256 "ce5bc5a5b50744f3beb4d01df33b9fad951df3fc53db98e6bf969c971a159050"

      def install
        bin.install "release-go"
      end
    end
  end
end
