# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Envq < Formula
  desc "Jq/yq-like tool for env files"
  homepage "https://github.com/tcurdt/envq"
  url "https://github.com/tcurdt/envq/archive/refs/tags/v0.0.4.tar.gz"
  sha256 "4e83ec8377217743bac113ed7eefcdbee8ef3fb025f5775e5dc996c009e1576d"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tcurdt/envq/releases/download/v0.0.4/envq-0.0.4-darwin-arm64.tar.gz"
      sha256 "2a6aaa1c89e9603362ba2023bce21f7d4f00cc85890322fe023ba50c6a220338"
    end
  end

  def install
    bin.install "envq"
  end

  test do
    assert_match "envq", shell_output("#{bin}/envq --help")

(testpath/"test.env").write("KEY=value\n")
assert_equal "value", shell_output("#{bin}/envq get KEY test.env").strip
  end
end
