# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Envq < Formula
  desc "Jq/yq-like tool for .env files"
  homepage "https://github.com/tcurdt/envq"
  url "https://github.com/tcurdt/envq/archive/refs/tags/v0.0.9.tar.gz"
  version "0.0.9"
  sha256 "e2fcd11e37923ecd984680af3a80ab78dabf2ad45e4a3df30c348b577493ffd2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tcurdt/envq/releases/download/v0.0.9/envq-0.0.9-darwin-arm64.tar.gz"
      sha256 "a7220bd0072be21d96b2b53ac0a9eecc543f94e5afe08cd65b4a2cca1dbdb503"
    end
  end

  def install
    bin.install "envq"
  end

  test do
    assert_match "envq", shell_output("#{bin}/envq --help")

    (testpath/"test.env").write("KEY=value\n")
    assert_equal "value", shell_output("#{bin}/envq get KEY test.env").strip
  end
end
