# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesops < Formula
  desc "Manage Kubernetes secrets as encrypted dotenv files"
  homepage "https://github.com/tcurdt/kubesops"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/kubesops/releases/download/v0.0.1/kubesops_Darwin_x86_64.tar.gz"
      sha256 "1a60b4e7e931d7227542ad416163860f6081cfef0c2b81282a667e1cb290291a"

      def install
        bin.install "kubesops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tcurdt/kubesops/releases/download/v0.0.1/kubesops_Darwin_arm64.tar.gz"
      sha256 "fd334a53429698eda1374a1aa10e46cdec19b7050ec90acc8861a6ceac27fe2c"

      def install
        bin.install "kubesops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/kubesops/releases/download/v0.0.1/kubesops_Linux_x86_64.tar.gz"
      sha256 "3aa9bab4abb07637dd18a2be8c7001ba77a3753e82cfb6aad66a082fd755586f"
      def install
        bin.install "kubesops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/kubesops/releases/download/v0.0.1/kubesops_Linux_arm64.tar.gz"
      sha256 "f503e1f802ecea953f59036a06423b6fb0a2891c3b193f5c6abc3f09aacadf02"
      def install
        bin.install "kubesops"
      end
    end
  end

  test do
    system "#{bin}/kubesops", "--help"
  end
end
