# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseGo < Formula
  desc "The description of the project
"
  homepage "https://github.com/tcurdt/release-go"
  version "1.0.1"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.1/release-go_1.0.1_darwin_arm64.zip"
      sha256 "2b3046a5fd62a45af5c26df92142af462385f627504892ef4094e37d45c9f890"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.1/release-go_1.0.1_darwin_amd64.zip"
      sha256 "5fd7f279c7ec6e78ded5bfd76a8f52bbd2d9b4ab16cf0b4f84ce867308306810"

      def install
        bin.install "release-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.1/release-go_1.0.1_linux_arm64.zip"
      sha256 "763228cf14320bdb3f7a4f2cac524f91c88c5986dfd067a0fe6ae207696fb5bb"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.1/release-go_1.0.1_linux_amd64.zip"
      sha256 "e57182c4e828d778c4f1a04029f2537044c0404a389df01d360af4d884624d90"

      def install
        bin.install "release-go"
      end
    end
  end
end
