# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseGo < Formula
  desc "The description of the project
"
  homepage "https://github.com/tcurdt/release-go"
  version "1.0.2"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.2/release-go_1.0.2_darwin_arm64.zip"
      sha256 "ca8a6edc8c95c1e2990ac32e0bd5b3f69a4d585018512db8762c47fdb30e74d8"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.2/release-go_1.0.2_darwin_amd64.zip"
      sha256 "aa815ab8e7914154f7e5d8c884f29069c8110632d8be04c5edcab254e0d5a1c1"

      def install
        bin.install "release-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.2/release-go_1.0.2_linux_arm64.zip"
      sha256 "ada861e00c3a178cf9be2f268128b4ba00a90b5c9576e11b23ce86cf6dc4d9f1"

      def install
        bin.install "release-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tcurdt/release-go/releases/download/v1.0.2/release-go_1.0.2_linux_amd64.zip"
      sha256 "ea126c778d13e7475598165219771df04dd2dba6b1dbbc98bd82d802116e66d7"

      def install
        bin.install "release-go"
      end
    end
  end
end
